version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=${PORT}
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_KEY=${SECRET_KEY}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
      - ENVIRONMENT=${ENVIRONMENT}
    volumes:
      - .:/usr/src/app
    command: ["npm", "start"]
